// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://malntcyyowkwrexywkfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hbG50Y3l5b3drd3JleHl3a2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTA5NzUsImV4cCI6MjA3MTQ2Njk3NX0.-oIPto87ohvHY0vjUJkjZ-cY3hFsXgLKCLpJt_pyF_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});